<template>
  <v-container >
  
    <h1 class="pe-text blue-text"> Cookies </h1>

    <BreadCrumbs  :items="breadcrumbs" />


    <h2 class="pe-text blue-text"> 
        What are cookies ?
    </h2>

    <p class="pe-text">
        Cookies refer to small pieces of data that a website sends to a user's web browser which is stored on the user's device.
        Cookies can e used to remember user preferences, keep track of items in a shopping kart or remember a user's login information
        for future visits. 
        <br><br>

        When a user visits a website, the server can send a cookie to the user's browser, which is then stored on the user's device. 
        On subsequent visits to the same website, the browser sends the cookie back to the server, allowing the website to remember the user's previous interactions.
    </p><br>

    <h2 class="pe-text blue-text">5 most common uses</h2>

    <li class="pe-text"> Session Management (e.g. cookie which ensures the user is logged while he navigates website)</li>
    <li class="pe-text"> Personalization (e.g. remember website language preference)</li>
    <li class="pe-text"> Analytics (e.g. collect data on how users interact with a website)</li>
    <li class="pe-text"> Advertising (e.g. Ad networks use cookes to track users across different websites and display relevant ads)</li>
    <li class="pe-text"> Security (can be used to prevent cross-site request forgery (CSRF) attacks.)</li>

    <br>
    <p class="pe-text">
      The 5 bullets above were generated by ChatGPT.
      In past projects I had used JWT to manage sessions after the users being authenticated on the backend hence I wanted to know the differences
      between cookies and JWT when it comes to session management. 
    </p>

    <br>

    <h2 class="pe-text blue-text">Differences between JWT and Cookies</h2>
    <br>

    <p>
    <li class="pe-text">Structure: JWT is a self-contained JSON object that contains claims (or statements) that can be used to identify and authenticate a user. Cookies, on the other hand, are small data files that are stored on the client's device and contain arbitrary data that can be read by the server. </li>
    <br>
    <li class="pe-text">Storage location: JWTs are typically stored in the client-side storage (e.g. browser's local storage or session storage), while cookies are stored in the browser's cookie jar. </li>
    <br>
    <li class="pe-text">Security: Both JWTs and cookies can be vulnerable to security threats such as cross-site scripting (XSS) attacks and cross-site request forgery (CSRF) attacks. However, JWTs have some advantages in terms of security, as they can be digitally signed and verified to ensure their authenticity and integrity. </li>
    <br>
    <li class="pe-text">Use cases: JWTs are often used for stateless authentication in APIs, where a client sends a JWT token with each API request to authenticate itself. Cookies, on the other hand, are often used for stateful authentication in web applications, where the server maintains a session state for each user and associates it with a cookie. </li>


    </p>



  </v-container>
</template>
<script>

import ArticleFigure from '../../../components/ArticleFigure.vue';
import BreadCrumbs from '../../../components/BreadCrumbs.vue';

export default {
  name: 'Cookies',
  components: {ArticleFigure,BreadCrumbs},
  data: () => ({
    breadcrumbs: [
      {"title": {"en":'Blog' ,  "pt": "Blog"},   "path":"/blog"},
      {"title": {"en":'Tech',   "pt": "Tech"},   "path":"/blog/tech"},
      {"title": {"en":'Cookies', "pt": "Cookies"}, "path":"/blog/tech/cookies"}
    ]})
}
</script>
<style lang="scss" scoped>
@import  "../../../styles/images.scss";
@import  "../../../styles/text.scss";
</style>